<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="45032" started-at="2019-02-24T07:11:26Z" finished-at="2019-02-24T07:12:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="45032" started-at="2019-02-24T07:11:26Z" finished-at="2019-02-24T07:12:11Z">
      <class name="com.crmpro.testCase.HelpPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.crmpro.testCase.HelpPageTest@6a41eaa2]" name="setUp" is-config="true" duration-ms="18191" started-at="2019-02-24T07:11:26Z" finished-at="2019-02-24T07:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="getLink()[pri:0, instance:com.crmpro.testCase.HelpPageTest@6a41eaa2]" name="getLink" duration-ms="7333" started-at="2019-02-24T07:11:44Z" finished-at="2019-02-24T07:11:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLink -->
        <test-method status="PASS" signature="closeDown()[pri:0, instance:com.crmpro.testCase.HelpPageTest@6a41eaa2]" name="closeDown" is-config="true" duration-ms="962" started-at="2019-02-24T07:11:51Z" finished-at="2019-02-24T07:11:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.crmpro.testCase.HelpPageTest@6a41eaa2]" name="setUp" is-config="true" duration-ms="14212" started-at="2019-02-24T07:11:52Z" finished-at="2019-02-24T07:12:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyHelpLink()[pri:0, instance:com.crmpro.testCase.HelpPageTest@6a41eaa2]" name="verifyHelpLink" duration-ms="2249" started-at="2019-02-24T07:12:07Z" finished-at="2019-02-24T07:12:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://support.cogmento.com/] but found [https://help.crmpro.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://support.cogmento.com/] but found [https://help.crmpro.com/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.crmpro.testCase.HelpPageTest.verifyHelpLink(HelpPageTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHelpLink -->
        <test-method status="PASS" signature="closeDown()[pri:0, instance:com.crmpro.testCase.HelpPageTest@6a41eaa2]" name="closeDown" is-config="true" duration-ms="1355" started-at="2019-02-24T07:12:09Z" finished-at="2019-02-24T07:12:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDown -->
      </class> <!-- com.crmpro.testCase.HelpPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
